version: '3.1'

services:

    greeter-service:
      build: ./srv/greeter-service
      ports:
        - 50051:50051
      environment:
        MICRO_ADDRESS: ":50051"
        MICRO_REGISTRY: "mdns"

    greeter-client:
      build: ./greeter-client
      environment:
        MICRO_REGISTRY: "mdns"

    